version: "3"
services:
  ollama-container:
    image: ollama/ollama:latest
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
  drunklingo:
    image: smartwhatt/drunklingo:0.1
    ports:
      - 8501:8501
